// AUTO-GENERATED by scripts/build-motion-presets.mjs.
// Do not edit directly — change the catalog in the script and re-run.
// CI runs the script with --check; drift fails the build.

import type { MotionPreset, RendererKind } from './types'

const ALL_RENDERERS: ReadonlyArray<RendererKind> = ['react', 'motion', 'lottie', 'three', 'canvas2d']

void ALL_RENDERERS

export const MOTION_PRESETS: ReadonlyArray<MotionPreset> = [
  {
    "id": "bounceIn",
    "category": "entrance",
    "description": "Spring-style bounce-in with overshoot",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "sx": 0.3,
        "sy": 0.3
      },
      {
        "at": 0.2,
        "sx": 1.1,
        "sy": 1.1
      },
      {
        "at": 0.4,
        "sx": 0.9,
        "sy": 0.9
      },
      {
        "at": 0.6,
        "opacity": 1,
        "sx": 1.03,
        "sy": 1.03
      },
      {
        "at": 0.8,
        "sx": 0.97,
        "sy": 0.97
      },
      {
        "at": 1,
        "opacity": 1,
        "sx": 1,
        "sy": 1
      }
    ]
  },
  {
    "id": "bounceInDown",
    "category": "entrance",
    "description": "Bounces down into place",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "ty": -3000
      },
      {
        "at": 0.6,
        "opacity": 1,
        "ty": 25
      },
      {
        "at": 0.75,
        "ty": -10
      },
      {
        "at": 0.9,
        "ty": 5
      },
      {
        "at": 1,
        "opacity": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "bounceInUp",
    "category": "entrance",
    "description": "Bounces up into place",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "ty": 3000
      },
      {
        "at": 0.6,
        "opacity": 1,
        "ty": -20
      },
      {
        "at": 0.75,
        "ty": 10
      },
      {
        "at": 0.9,
        "ty": -5
      },
      {
        "at": 1,
        "opacity": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "fadeIn",
    "category": "entrance",
    "description": "Plain fade-in",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0
      },
      {
        "at": 1,
        "opacity": 1
      }
    ]
  },
  {
    "id": "fadeInDown",
    "category": "entrance",
    "description": "Fade in while sliding down from above",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "ty": -60
      },
      {
        "at": 1,
        "opacity": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "fadeInDownBig",
    "category": "entrance",
    "description": "Bigger fade-in slide-down",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "ty": -200
      },
      {
        "at": 1,
        "opacity": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "fadeInLeft",
    "category": "entrance",
    "description": "Fade in while sliding right from the left",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "tx": -60
      },
      {
        "at": 1,
        "opacity": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "fadeInLeftBig",
    "category": "entrance",
    "description": "Bigger fade-in slide-from-left",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "tx": -200
      },
      {
        "at": 1,
        "opacity": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "fadeInRight",
    "category": "entrance",
    "description": "Fade in while sliding left from the right",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "tx": 60
      },
      {
        "at": 1,
        "opacity": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "fadeInRightBig",
    "category": "entrance",
    "description": "Bigger fade-in slide-from-right",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "tx": 200
      },
      {
        "at": 1,
        "opacity": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "fadeInUp",
    "category": "entrance",
    "description": "Fade in while sliding up from below",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "ty": 60
      },
      {
        "at": 1,
        "opacity": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "fadeInUpBig",
    "category": "entrance",
    "description": "Bigger fade-in slide-up — more dramatic",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "ty": 200
      },
      {
        "at": 1,
        "opacity": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "jackInTheBox",
    "category": "entrance",
    "description": "Springy reveal that twists into place",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion"
    ],
    "flags": {
      "layoutAware": true,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "sx": 0.1,
        "sy": 0.1,
        "rot": 30
      },
      {
        "at": 0.5,
        "rot": -10
      },
      {
        "at": 0.7,
        "rot": 3
      },
      {
        "at": 1,
        "opacity": 1,
        "sx": 1,
        "sy": 1,
        "rot": 0
      }
    ]
  },
  {
    "id": "lightSpeedInLeft",
    "category": "entrance",
    "description": "Skews in from the left like light-speed motion",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion"
    ],
    "flags": {
      "layoutAware": true,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "tx": -200,
        "rot": -30
      },
      {
        "at": 0.6,
        "opacity": 1,
        "rot": 20
      },
      {
        "at": 0.8,
        "rot": -5
      },
      {
        "at": 1,
        "opacity": 1,
        "tx": 0,
        "rot": 0
      }
    ]
  },
  {
    "id": "lightSpeedInRight",
    "category": "entrance",
    "description": "Skews in from the right like light-speed motion",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion"
    ],
    "flags": {
      "layoutAware": true,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "tx": 200,
        "rot": 30
      },
      {
        "at": 0.6,
        "opacity": 1,
        "rot": -20
      },
      {
        "at": 0.8,
        "rot": 5
      },
      {
        "at": 1,
        "opacity": 1,
        "tx": 0,
        "rot": 0
      }
    ]
  },
  {
    "id": "rollIn",
    "category": "entrance",
    "description": "Rolls in from the left while rotating",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion"
    ],
    "flags": {
      "layoutAware": true,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "tx": -200,
        "rot": -120
      },
      {
        "at": 1,
        "opacity": 1,
        "tx": 0,
        "rot": 0
      }
    ]
  },
  {
    "id": "rotateIn",
    "category": "entrance",
    "description": "Rotates in 200 degrees while fading",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "rot": -200
      },
      {
        "at": 1,
        "opacity": 1,
        "rot": 0
      }
    ]
  },
  {
    "id": "rotateInDownLeft",
    "category": "entrance",
    "description": "Rotates down-left into place",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "rot": -45,
        "tx": -100,
        "ty": -50
      },
      {
        "at": 1,
        "opacity": 1,
        "rot": 0,
        "tx": 0,
        "ty": 0
      }
    ]
  },
  {
    "id": "rotateInUpRight",
    "category": "entrance",
    "description": "Rotates up-right into place",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "rot": -90,
        "tx": 100,
        "ty": 50
      },
      {
        "at": 1,
        "opacity": 1,
        "rot": 0,
        "tx": 0,
        "ty": 0
      }
    ]
  },
  {
    "id": "slideInDown",
    "category": "entrance",
    "description": "Slide in from above — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "ty": -200
      },
      {
        "at": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "slideInLeft",
    "category": "entrance",
    "description": "Slide in from the left — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "tx": -200
      },
      {
        "at": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "slideInRight",
    "category": "entrance",
    "description": "Slide in from the right — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "tx": 200
      },
      {
        "at": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "slideInUp",
    "category": "entrance",
    "description": "Slide in from below — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "ty": 200
      },
      {
        "at": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "zoomIn",
    "category": "entrance",
    "description": "Scale up from 30% with fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "sx": 0.3,
        "sy": 0.3
      },
      {
        "at": 1,
        "opacity": 1,
        "sx": 1,
        "sy": 1
      }
    ]
  },
  {
    "id": "zoomInDown",
    "category": "entrance",
    "description": "Zoom down — scales while sliding from above",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "sx": 0.1,
        "sy": 0.1,
        "ty": -1000
      },
      {
        "at": 0.6,
        "opacity": 1,
        "sx": 0.475,
        "sy": 0.475,
        "ty": 60
      },
      {
        "at": 1,
        "opacity": 1,
        "sx": 1,
        "sy": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "zoomInLeft",
    "category": "entrance",
    "description": "Zoom in from the left",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "sx": 0.1,
        "sy": 0.1,
        "tx": -1000
      },
      {
        "at": 0.6,
        "opacity": 1,
        "sx": 0.475,
        "sy": 0.475,
        "tx": 10
      },
      {
        "at": 1,
        "opacity": 1,
        "sx": 1,
        "sy": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "zoomInRight",
    "category": "entrance",
    "description": "Zoom in from the right",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "sx": 0.1,
        "sy": 0.1,
        "tx": 1000
      },
      {
        "at": 0.6,
        "opacity": 1,
        "sx": 0.475,
        "sy": 0.475,
        "tx": -10
      },
      {
        "at": 1,
        "opacity": 1,
        "sx": 1,
        "sy": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "zoomInUp",
    "category": "entrance",
    "description": "Zoom up — scales while sliding from below",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.out",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0,
        "sx": 0.1,
        "sy": 0.1,
        "ty": 1000
      },
      {
        "at": 0.6,
        "opacity": 1,
        "sx": 0.475,
        "sy": 0.475,
        "ty": -60
      },
      {
        "at": 1,
        "opacity": 1,
        "sx": 1,
        "sy": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "bounceOut",
    "category": "exit",
    "description": "Bounces while collapsing to nothing",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 0.2,
        "sx": 0.9,
        "sy": 0.9
      },
      {
        "at": 0.5,
        "opacity": 1,
        "sx": 1.1,
        "sy": 1.1
      },
      {
        "at": 0.55,
        "sx": 1.1,
        "sy": 1.1
      },
      {
        "at": 1,
        "opacity": 0,
        "sx": 0.3,
        "sy": 0.3
      }
    ]
  },
  {
    "id": "fadeOut",
    "category": "exit",
    "description": "Plain fade-out",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1
      },
      {
        "at": 1,
        "opacity": 0
      }
    ]
  },
  {
    "id": "fadeOutDown",
    "category": "exit",
    "description": "Fade out while sliding down",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "ty": 0
      },
      {
        "at": 1,
        "opacity": 0,
        "ty": 60
      }
    ]
  },
  {
    "id": "fadeOutLeft",
    "category": "exit",
    "description": "Fade out while sliding left",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "tx": 0
      },
      {
        "at": 1,
        "opacity": 0,
        "tx": -60
      }
    ]
  },
  {
    "id": "fadeOutRight",
    "category": "exit",
    "description": "Fade out while sliding right",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "tx": 0
      },
      {
        "at": 1,
        "opacity": 0,
        "tx": 60
      }
    ]
  },
  {
    "id": "fadeOutUp",
    "category": "exit",
    "description": "Fade out while sliding up",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "ty": 0
      },
      {
        "at": 1,
        "opacity": 0,
        "ty": -60
      }
    ]
  },
  {
    "id": "hinge",
    "category": "exit",
    "description": "Swings on a hinge then drops off-screen",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion"
    ],
    "flags": {
      "layoutAware": true,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "rot": 0,
        "ty": 0
      },
      {
        "at": 0.2,
        "rot": 80
      },
      {
        "at": 0.4,
        "rot": 60
      },
      {
        "at": 0.6,
        "rot": 80
      },
      {
        "at": 0.8,
        "opacity": 1,
        "rot": 60,
        "ty": 0
      },
      {
        "at": 1,
        "opacity": 0,
        "rot": 60,
        "ty": 700
      }
    ]
  },
  {
    "id": "rollOut",
    "category": "exit",
    "description": "Rolls out to the right while rotating",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion"
    ],
    "flags": {
      "layoutAware": true,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "tx": 0,
        "rot": 0
      },
      {
        "at": 1,
        "opacity": 0,
        "tx": 200,
        "rot": 120
      }
    ]
  },
  {
    "id": "rotateOut",
    "category": "exit",
    "description": "Rotates 200 degrees while fading out",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "rot": 0
      },
      {
        "at": 1,
        "opacity": 0,
        "rot": 200
      }
    ]
  },
  {
    "id": "slideOutDown",
    "category": "exit",
    "description": "Slide out down — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "ty": 0
      },
      {
        "at": 1,
        "ty": 200
      }
    ]
  },
  {
    "id": "slideOutLeft",
    "category": "exit",
    "description": "Slide out left — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "tx": 0
      },
      {
        "at": 1,
        "tx": -200
      }
    ]
  },
  {
    "id": "slideOutRight",
    "category": "exit",
    "description": "Slide out right — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "tx": 0
      },
      {
        "at": 1,
        "tx": 200
      }
    ]
  },
  {
    "id": "slideOutUp",
    "category": "exit",
    "description": "Slide out up — no fade",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "ty": 0
      },
      {
        "at": 1,
        "ty": -200
      }
    ]
  },
  {
    "id": "zoomOut",
    "category": "exit",
    "description": "Scale down to 30% while fading",
    "defaultDurationFrames": 18,
    "defaultEasing": "power2.in",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 0.5,
        "opacity": 0,
        "sx": 0.3,
        "sy": 0.3
      },
      {
        "at": 1,
        "opacity": 0
      }
    ]
  },
  {
    "id": "bounce",
    "category": "emphasis",
    "description": "Bouncing ball — vertical hops with damping",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "ty": 0
      },
      {
        "at": 0.2,
        "ty": 0
      },
      {
        "at": 0.4,
        "ty": -30
      },
      {
        "at": 0.43,
        "ty": -30
      },
      {
        "at": 0.53,
        "ty": 0
      },
      {
        "at": 0.7,
        "ty": -15
      },
      {
        "at": 0.8,
        "ty": 0
      },
      {
        "at": 0.9,
        "ty": -4
      },
      {
        "at": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "flash",
    "category": "emphasis",
    "description": "Strobe flash — opacity blink",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 1
      },
      {
        "at": 0.25,
        "opacity": 0
      },
      {
        "at": 0.5,
        "opacity": 1
      },
      {
        "at": 0.75,
        "opacity": 0
      },
      {
        "at": 1,
        "opacity": 1
      }
    ]
  },
  {
    "id": "heartBeat",
    "category": "emphasis",
    "description": "Two-beat heart-rhythm pulse",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 0.14,
        "sx": 1.3,
        "sy": 1.3
      },
      {
        "at": 0.28,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 0.42,
        "sx": 1.3,
        "sy": 1.3
      },
      {
        "at": 0.7,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 1,
        "sx": 1,
        "sy": 1
      }
    ]
  },
  {
    "id": "jello",
    "category": "emphasis",
    "description": "Wobbles like jello — diminishing skew",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "rot": 0
      },
      {
        "at": 0.111,
        "rot": 0
      },
      {
        "at": 0.222,
        "rot": -12.5
      },
      {
        "at": 0.333,
        "rot": 6.25
      },
      {
        "at": 0.444,
        "rot": -3.125
      },
      {
        "at": 0.555,
        "rot": 1.5625
      },
      {
        "at": 0.666,
        "rot": -0.78125
      },
      {
        "at": 0.777,
        "rot": 0.390625
      },
      {
        "at": 0.888,
        "rot": -0.1953125
      },
      {
        "at": 1,
        "rot": 0
      }
    ]
  },
  {
    "id": "pulse",
    "category": "emphasis",
    "description": "Subtle scale pulse — call attention without distraction",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 0.5,
        "sx": 1.05,
        "sy": 1.05
      },
      {
        "at": 1,
        "sx": 1,
        "sy": 1
      }
    ]
  },
  {
    "id": "rubberBand",
    "category": "emphasis",
    "description": "Stretch + squash like rubber",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 0.3,
        "sx": 1.25,
        "sy": 0.75
      },
      {
        "at": 0.4,
        "sx": 0.75,
        "sy": 1.25
      },
      {
        "at": 0.5,
        "sx": 1.15,
        "sy": 0.85
      },
      {
        "at": 0.65,
        "sx": 0.95,
        "sy": 1.05
      },
      {
        "at": 0.75,
        "sx": 1.05,
        "sy": 0.95
      },
      {
        "at": 1,
        "sx": 1,
        "sy": 1
      }
    ]
  },
  {
    "id": "shake",
    "category": "emphasis",
    "description": "Side-to-side shake — error / warning emphasis",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "tx": 0
      },
      {
        "at": 0.1,
        "tx": -10
      },
      {
        "at": 0.2,
        "tx": 10
      },
      {
        "at": 0.3,
        "tx": -10
      },
      {
        "at": 0.4,
        "tx": 10
      },
      {
        "at": 0.5,
        "tx": -10
      },
      {
        "at": 0.6,
        "tx": 10
      },
      {
        "at": 0.7,
        "tx": -10
      },
      {
        "at": 0.8,
        "tx": 10
      },
      {
        "at": 0.9,
        "tx": -10
      },
      {
        "at": 1,
        "tx": 0
      }
    ]
  },
  {
    "id": "shakeY",
    "category": "emphasis",
    "description": "Vertical shake — emphasis variant",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "ty": 0
      },
      {
        "at": 0.1,
        "ty": -10
      },
      {
        "at": 0.2,
        "ty": 10
      },
      {
        "at": 0.3,
        "ty": -10
      },
      {
        "at": 0.4,
        "ty": 10
      },
      {
        "at": 0.5,
        "ty": -10
      },
      {
        "at": 0.6,
        "ty": 10
      },
      {
        "at": 0.7,
        "ty": -10
      },
      {
        "at": 0.8,
        "ty": 10
      },
      {
        "at": 0.9,
        "ty": -10
      },
      {
        "at": 1,
        "ty": 0
      }
    ]
  },
  {
    "id": "swing",
    "category": "emphasis",
    "description": "Rocks back and forth like a pendulum",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "rot": 0
      },
      {
        "at": 0.2,
        "rot": 15
      },
      {
        "at": 0.4,
        "rot": -10
      },
      {
        "at": 0.6,
        "rot": 5
      },
      {
        "at": 0.8,
        "rot": -5
      },
      {
        "at": 1,
        "rot": 0
      }
    ]
  },
  {
    "id": "tada",
    "category": "emphasis",
    "description": "Celebration wiggle — scale up then twist back and forth",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "sx": 1,
        "sy": 1,
        "rot": 0
      },
      {
        "at": 0.1,
        "sx": 0.9,
        "sy": 0.9,
        "rot": -3
      },
      {
        "at": 0.2,
        "sx": 0.9,
        "sy": 0.9,
        "rot": -3
      },
      {
        "at": 0.3,
        "sx": 1.1,
        "sy": 1.1,
        "rot": 3
      },
      {
        "at": 0.4,
        "sx": 1.1,
        "sy": 1.1,
        "rot": -3
      },
      {
        "at": 0.5,
        "sx": 1.1,
        "sy": 1.1,
        "rot": 3
      },
      {
        "at": 0.6,
        "sx": 1.1,
        "sy": 1.1,
        "rot": -3
      },
      {
        "at": 0.7,
        "sx": 1.1,
        "sy": 1.1,
        "rot": 3
      },
      {
        "at": 0.8,
        "sx": 1.1,
        "sy": 1.1,
        "rot": -3
      },
      {
        "at": 0.9,
        "sx": 1.1,
        "sy": 1.1,
        "rot": 3
      },
      {
        "at": 1,
        "sx": 1,
        "sy": 1,
        "rot": 0
      }
    ]
  },
  {
    "id": "wobble",
    "category": "emphasis",
    "description": "Oscillates side to side with diminishing amplitude",
    "defaultDurationFrames": 24,
    "defaultEasing": "power1.inOut",
    "compatibleRenderers": [
      "react",
      "motion",
      "lottie",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "tx": 0,
        "rot": 0
      },
      {
        "at": 0.15,
        "tx": -25,
        "rot": -5
      },
      {
        "at": 0.3,
        "tx": 20,
        "rot": 3
      },
      {
        "at": 0.45,
        "tx": -15,
        "rot": -3
      },
      {
        "at": 0.6,
        "tx": 10,
        "rot": 2
      },
      {
        "at": 0.75,
        "tx": -5,
        "rot": -1
      },
      {
        "at": 1,
        "tx": 0,
        "rot": 0
      }
    ]
  },
  {
    "id": "ambientPulse",
    "category": "ambient",
    "description": "Subtle opacity pulse — looped",
    "defaultDurationFrames": 120,
    "defaultEasing": "ease-in-out",
    "compatibleRenderers": [
      "react",
      "motion",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "opacity": 0.85
      },
      {
        "at": 0.5,
        "opacity": 1
      },
      {
        "at": 1,
        "opacity": 0.85
      }
    ]
  },
  {
    "id": "breathe",
    "category": "ambient",
    "description": "Gentle scale breathing — looped",
    "defaultDurationFrames": 180,
    "defaultEasing": "ease-in-out",
    "compatibleRenderers": [
      "react",
      "motion",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "sx": 1,
        "sy": 1
      },
      {
        "at": 0.5,
        "sx": 1.04,
        "sy": 1.04
      },
      {
        "at": 1,
        "sx": 1,
        "sy": 1
      }
    ]
  },
  {
    "id": "drift",
    "category": "ambient",
    "description": "Slow continuous drift — looped background motion",
    "defaultDurationFrames": 240,
    "defaultEasing": "ease-in-out",
    "compatibleRenderers": [
      "react",
      "motion",
      "three",
      "canvas2d"
    ],
    "flags": {
      "layoutAware": false,
      "textDecomposition": false
    },
    "keyframes": [
      {
        "at": 0,
        "tx": 0,
        "ty": 0
      },
      {
        "at": 0.5,
        "tx": 8,
        "ty": -4
      },
      {
        "at": 1,
        "tx": 0,
        "ty": 0
      }
    ]
  }
] as const

export const MOTION_PRESET_IDS: ReadonlyArray<string> = MOTION_PRESETS.map((p) => p.id)

export function getMotionPreset(id: string): MotionPreset | null {
  return MOTION_PRESETS.find((p) => p.id === id) ?? null
}

export function listMotionPresets(filter?: { category?: MotionPreset['category']; renderer?: RendererKind }): ReadonlyArray<MotionPreset> {
  if (!filter) return MOTION_PRESETS
  return MOTION_PRESETS.filter((p) => {
    if (filter.category && p.category !== filter.category) return false
    if (filter.renderer && !p.compatibleRenderers.includes(filter.renderer)) return false
    return true
  })
}
