/**
 * Silence → action-sequence coordinator.
 *
 * Given a clip and a set of silence spans (clip-relative seconds, output
 * of `detectSilenceSpans`), build the sequence of `ActionInput`s that
 * cut those silences out. The agent / UI then dispatches the sequence
 * through the action layer — each step is normal `clip/split` +
 * `clip/rippleDelete`, so undo + action_log work for free.
 *
 * Algorithm (process spans in reverse so left/middle ids stay stable):
 *
 *   for each silence span [s, e] in reverse:
 *     if span covers the whole clip → emit one clip/rippleDelete; done
 *     else if span starts at clip head (s ≈ 0):
 *       emit clip/split at e
 *       emit clip/rippleDelete on the left half
 *     else if span ends at clip tail (e ≈ clip.duration):
 *       emit clip/split at s
 *       emit clip/rippleDelete on the right half
 *     else:
 *       emit clip/split at s             → left half = clip
 *       emit clip/split at (e - s) on the right half
 *       emit clip/rippleDelete on the middle (the new right-of-split)
 *
 * Reverse order means earlier spans' splits don't shift the indices of
 * later spans' references — the same id we operated on stays valid.
 *
 * Pure — no Zustand, no dispatch. Returns a typed list of action inputs
 * the caller hands to `dispatchAction` (or to `executeTool` / IPC). IDs
 * for newly-split halves are generated by the caller; we surface them
 * via `splitIdHints` so an agent run can label each fragment.
 */

import type { ActionInput } from '@/lib/actions'
import type { Clip } from '@/lib/types'

export interface SilenceSpanForCut {
  start: number
  end: number
}

export interface SilenceCutOptions {
  /** Caller-provided unique-id factory; default is a counter-based string for tests. */
  newId?: () => string
  /** Snap-to-zero tolerance in seconds. Spans within `epsilon` of clip edges count as edge-aligned. */
  epsilon?: number
}

export interface SilenceCutPlan {
  /** Ordered list of action inputs the caller dispatches in sequence. */
  actions: ActionInput[]
  /** Per-split id hint so the caller can preserve naming if it wants. */
  splitIdHints: string[]
  /**
   * Sum of silence duration removed (seconds). Surface to the user as the
   * "saved 28s" affordance shown after auto-cut.
   */
  savedSeconds: number
}

const DEFAULT_EPSILON = 0.01

function defaultIdCounter(): () => string {
  let i = 0
  return () => `kf-split-${++i}`
}

/**
 * Build the action sequence for a single clip. `spans` are clip-relative
 * seconds (matches `detectSilenceSpans` output).
 */
export function silenceSpansToActions(
  clip: Clip,
  spans: SilenceSpanForCut[],
  options: SilenceCutOptions = {},
): SilenceCutPlan {
  if (spans.length === 0) {
    return { actions: [], splitIdHints: [], savedSeconds: 0 }
  }
  const epsilon = options.epsilon ?? DEFAULT_EPSILON
  const newId = options.newId ?? defaultIdCounter()

  // Sort + clip + merge adjacent/overlapping spans so we don't double-cut.
  const sanitized = sanitizeSpans(spans, clip.duration, epsilon)
  if (sanitized.length === 0) {
    return { actions: [], splitIdHints: [], savedSeconds: 0 }
  }

  // Whole-clip cover → one ripple-delete.
  if (sanitized.length === 1) {
    const s = sanitized[0]
    if (s.start <= epsilon && s.end >= clip.duration - epsilon) {
      return {
        actions: [{ type: 'clip/rippleDelete', params: { clipId: clip.id } }],
        splitIdHints: [],
        savedSeconds: s.end - s.start,
      }
    }
  }

  // Process spans in reverse so left/middle clip ids remain stable across
  // earlier cuts.
  const actions: ActionInput[] = []
  const splitIdHints: string[] = []
  let savedSeconds = 0
  // Working duration shrinks as we delete; we always operate against the
  // *original* clip id for the head-anchored cuts since split's left half
  // keeps the id. Track the current clip id as it can change after a
  // head-trim split.
  let workingClipId = clip.id

  for (let i = sanitized.length - 1; i >= 0; i--) {
    const span = sanitized[i]
    savedSeconds += span.end - span.start

    const headAligned = span.start <= epsilon
    const tailAligned = span.end >= clip.duration - epsilon

    if (headAligned) {
      // [0, e]  — split at `e`; ripple-delete the left half.
      const rightId = newId()
      splitIdHints.push(rightId)
      actions.push({
        type: 'clip/split',
        params: { clipId: workingClipId, time: clip.startTime + span.end, rightClipId: rightId },
      })
      actions.push({ type: 'clip/rippleDelete', params: { clipId: workingClipId } })
      // After this delete, what was the right half is now the clip the
      // user thinks of as "the rest". We continue to operate on
      // workingClipId... but workingClipId was just deleted. Since we're
      // walking in reverse and head-aligned spans are the leftmost, this
      // means we're processing the last cut. Stop.
      workingClipId = rightId
    } else if (tailAligned) {
      // [s, duration]  — split at `s`; ripple-delete the right half.
      const rightId = newId()
      splitIdHints.push(rightId)
      actions.push({
        type: 'clip/split',
        params: { clipId: workingClipId, time: clip.startTime + span.start, rightClipId: rightId },
      })
      actions.push({ type: 'clip/rippleDelete', params: { clipId: rightId } })
    } else {
      // [s, e] strictly inside — split at `s`, then split right-half at the
      // span length, then ripple-delete the new middle.
      const rightOfFirst = newId()
      const middleRight = newId()
      splitIdHints.push(rightOfFirst, middleRight)
      actions.push({
        type: 'clip/split',
        params: { clipId: workingClipId, time: clip.startTime + span.start, rightClipId: rightOfFirst },
      })
      // Right-half's local 0 starts at `s` in source coords, so the silence
      // ends at offset (e - s) into the right-half.
      actions.push({
        type: 'clip/split',
        params: { clipId: rightOfFirst, time: clip.startTime + span.end, rightClipId: middleRight },
      })
      actions.push({ type: 'clip/rippleDelete', params: { clipId: rightOfFirst } })
    }
  }

  return { actions, splitIdHints, savedSeconds }
}

// ── helpers ────────────────────────────────────────────────────────────────

/**
 * Clip spans to [0, duration], drop zero-length, sort ascending, and merge
 * overlapping / adjacent (within epsilon) spans. Returns a fresh array;
 * never mutates the input.
 */
function sanitizeSpans(spans: SilenceSpanForCut[], duration: number, epsilon: number): SilenceSpanForCut[] {
  const clamped = spans
    .map((s) => ({ start: Math.max(0, Math.min(duration, s.start)), end: Math.max(0, Math.min(duration, s.end)) }))
    .filter((s) => s.end - s.start > epsilon)
    .sort((a, b) => a.start - b.start)

  if (clamped.length === 0) return clamped

  const merged: SilenceSpanForCut[] = [clamped[0]]
  for (let i = 1; i < clamped.length; i++) {
    const last = merged[merged.length - 1]
    const cur = clamped[i]
    if (cur.start <= last.end + epsilon) {
      // overlap / adjacent → extend
      last.end = Math.max(last.end, cur.end)
    } else {
      merged.push(cur)
    }
  }
  return merged
}
