import type { SceneType } from './scene'
import type { InteractionElement, SceneVariable } from './interaction'
import type { AudioSettings } from './audio'
import type { WatermarkConfig, BrandKit } from './media'
import type { APIPermissions } from './permissions'
import type { TransitionType } from '../transitions'
import type { Timeline } from './timeline'
import type { AspectRatio } from '../dimensions'

export type StylePresetId =
  | 'whiteboard'
  | 'chalkboard'
  | 'blueprint'
  | 'clean'
  | 'data-story'
  | 'newspaper'
  | 'neon'
  | 'kraft'
  | 'threeblueonebrown'
  | 'feynman'
  | 'cinematic'
  | 'pencil'
  | 'risograph'
  | 'retro_terminal'
  | 'science_journal'
  | 'pastel_edu'

export type PlatformProfileId =
  | 'custom'
  | 'youtube-landscape'
  | 'youtube-shorts'
  | 'instagram-reel'
  | 'instagram-feed'
  | 'tiktok'
  | 'linkedin-feed'
  | 'twitter-post'
  | 'cinematic-21-9'

export interface GlobalStyle {
  presetId: StylePresetId | null

  // Optional per-project overrides (null = use preset default)
  paletteOverride: [string, string, string, string] | null
  bgColorOverride: string | null
  fontOverride: string | null
  bodyFontOverride: string | null
  strokeColorOverride: string | null

  // Legacy fields — kept for migration compatibility
  palette?: [string, string, string, string, string]
  strokeWidth?: number
  font?: string
  duration?: number
  theme?: 'dark' | 'light' | 'blue'

  /** App chrome typography (panels, settings). Not used for generated scene text. */
  uiTypography?: 'system' | 'app' | 'custom'
  /** When `uiTypography` is `custom`, font family from the studio catalog. */
  uiFontFamily?: string | null
  /** UI text size scale: 0 = compact, 1 = default, 2 = large, 3 = extra-large */
  uiTextSize?: number

  /** Motion personality for consistent animation feel across scenes. */
  motionPersonality?: 'playful' | 'premium' | 'corporate' | 'energetic' | null

  /** Project-specific design brief generated by the create_design_brief tool.
   *  Follows the Google design.md format: YAML frontmatter with exact token
   *  values (colors, typography, spacing, rounded, components) + 8 canonical
   *  prose sections. Injected into every scene-authoring turn so the agent
   *  builds with a consistent visual identity for this specific project. */
  designBrief?: string | null
}

// ── ProjectBrief (OKF Layer 0 — intent / the "compass") ──────────────────────
// INTENT, not style. `GlobalStyle.designBrief` above owns how the project LOOKS
// (DESIGN.md tokens); ProjectBrief owns WHAT it is and what it's FOR: format,
// video type, the log line, who drives the voice, and the media strategy. It is
// the durable project-level memory the agent routes from. Phase A: persisted + injected every
// turn, advisory only — no routing/behavior change yet.

export type VideoType =
  | 'film'
  | 'marketing'
  | 'explainer'
  | 'educational'
  | 'professional'
  | 'podcast'
  | 'shortform'
  | 'other'

export type VoiceDriver = 'narration-led' | 'visual-led' | 'dialogue-led'

export interface MediaStrategy {
  /** Pull real-world facts / references before building. */
  research: boolean
  /** Source stock images / video. */
  stock: boolean
  /** Use generation models for clips / images / effects. */
  generate: boolean
  /** Compose from the user's own uploaded assets. */
  userAssets: boolean
  /** Apply a brand kit. */
  branding: boolean
  overlays: {
    captions: boolean
    stickers: boolean
    svgs: boolean
    lowerThirds: boolean
  }
}

export interface ProjectBrief {
  // ── format ──
  aspectRatio: AspectRatio
  /** Derived from aspectRatio + runtimeTargetSec; routes the short/long lane. */
  lengthClass: 'shortform' | 'longform'
  /** User's runtime goal in seconds; null = agent proposes one. */
  runtimeTargetSec: number | null

  // ── intent (Mace's log line — the compass) ──
  videoType: VideoType
  /** One-line compass: problem → intention → obstacle → solution, compressed. */
  logLine: string
  intent: {
    problem: string
    intention: string
    obstacle: string
    solution: string
  } | null
  audience: string
  title?: string
  /** Shortform / upload only. */
  thumbnailConcept?: string

  // ── drivers (route the decision tree in later phases) ──
  voiceDriver: VoiceDriver
  hasUploadedFootage: boolean
  /** Uploaded footage carries spoken audio (drives the footage-edit lane). */
  footageHasSpeech: boolean
  isAvatarCentric: boolean
  mediaStrategy: MediaStrategy

  // ── provenance + memory ──
  source: 'user-explicit' | 'agent-inferred'
  /** 0–1 confidence for agent-inferred fields; low → confirm with user first. */
  confidence: number
  version: number
}

export type ExportResolution = '720p' | '1080p' | '4k'
/** Single source of truth for supported export frame rates — the runtime
 *  allowlist (normalizeExportSettings) derives from this same tuple, so the
 *  type and the snapping logic can't drift. */
export const EXPORT_FPS = [24, 25, 30, 60] as const
export type ExportFPS = (typeof EXPORT_FPS)[number]

export interface ExportSettings {
  resolution: ExportResolution
  fps: ExportFPS
  format: 'mp4'
  outputName?: string
  profile?: 'fast' | 'quality'
  /** Skip save dialog, write directly to this path (headless/API export). */
  outputPath?: string
  /** Hardcode the project's TTS captions into the video pixels (one extra
   *  re-encode at the end). Sidecar .srt/.vtt files ship regardless. */
  burnCaptions?: boolean
  /**
   * Capture engine. 'legacy' = Pixi + WebCodecs + html2canvas (per-scene).
   * 'tier3' = real-compositor offscreen capture + single FFmpeg pass (main
   * process) — fixes gradient banding / softness. Falls back to legacy for
   * scenes with a video layer (deterministic seek can't sync HTML <video>).
   */
  engine?: 'legacy' | 'tier3'
}

export interface ExportProgress {
  phase: 'rendering' | 'mixing_audio' | 'stitching' | 'complete' | 'error' | 'cancelled'
  currentScene: number
  totalScenes: number
  sceneProgress: number // 0–100
  downloadUrl: string | null
  /** Absolute file path of the written MP4 (Electron only). */
  filePath?: string | null
  error: string | null
  /**
   * 11b — which scene the export died on (1-based; null when the failure
   * wasn't scene-scoped, e.g. concat/stitch/normalize). Lets the agent
   * re-generate just the broken scene instead of guessing from a bare string.
   */
  errorSceneIndex?: number | null
  errorSceneId?: string | null
  /**
   * Non-fatal degradation the user must see on the success screen (e.g.
   * "exported WITHOUT burned captions") — phase stays 'complete', but the
   * completion UI renders this as a warning instead of burying it in
   * diagnostics.
   */
  warning?: string | null
  diagnostics?: string[]
}

// ── Project / Scene Graph ────────────────────────────────────────────────────

export interface SceneNode {
  id: string // matches scene.id
  position: { x: number; y: number }
}

export interface EdgeCondition {
  type: 'auto' | 'hotspot' | 'choice' | 'quiz' | 'gate' | 'variable' | 'slider' | 'toggle'
  interactionId: string | null
  variableName: string | null
  variableValue: string | null
  /** Rich condition — when set, takes precedence over variableName/variableValue equality check */
  variableCondition?: import('./interaction').VariableCondition | null
}

export interface SceneEdge {
  id: string
  fromSceneId: string
  toSceneId: string
  condition: EdgeCondition
}

export interface SceneGraph {
  nodes: SceneNode[]
  edges: SceneEdge[]
  startSceneId: string
}

export interface MP4Settings {
  resolution: '720p' | '1080p' | '4k'
  fps: 24 | 25 | 30 | 60
  format: 'mp4' | 'webm'
  aspectRatio?: AspectRatio
  /** Last-selected platform profile (YouTube, TikTok, etc.). `null` or
   *  omitted means Custom. Persisted so re-opening the export modal
   *  remembers the user's target destination. */
  platformProfileId?: PlatformProfileId | null
}

export interface InteractiveSettings {
  playerTheme: 'dark' | 'light' | 'transparent'
  showProgressBar: boolean
  showSceneNav: boolean
  allowFullscreen: boolean
  brandColor: string
  customDomain: string | null
  password: string | null
}

// ── Player types (shared with packages/player) ───────────────────────────────

export interface PlayerOptions {
  theme: 'dark' | 'light' | 'transparent'
  showProgressBar: boolean
  showSceneNav: boolean
  allowFullscreen: boolean
  brandColor: string
  autoplay: boolean
}

export interface PublishedScene {
  id: string
  type: SceneType
  duration: number
  htmlUrl: string
  htmlContent: string | null
  interactions: InteractionElement[]
  variables: SceneVariable[]
  transition: TransitionType
}

export interface PublishedProject {
  id: string
  version: number
  name: string
  playerOptions: PlayerOptions
  sceneGraph: SceneGraph
  scenes: PublishedScene[]
}

export interface Project {
  id: string
  name: string
  outputMode: 'mp4' | 'interactive'
  createdAt: string
  updatedAt: string

  mp4Settings: MP4Settings

  interactiveSettings: {
    playerTheme: 'dark' | 'light' | 'transparent'
    showProgressBar: boolean
    showSceneNav: boolean
    allowFullscreen: boolean
    brandColor: string
    customDomain: string | null
    password: string | null
  }

  sceneGraph: SceneGraph
  apiPermissions: APIPermissions
  audioSettings: AudioSettings
  audioProviderEnabled: Record<string, boolean>
  mediaGenEnabled: Record<string, boolean>
  watermark: WatermarkConfig | null
  brandKit: BrandKit | null
  pausedAgentRun?: {
    toolName: string
    toolInput: Record<string, unknown>
    agentType?: string | null
    reason?: string | null
    createdAt: string
  } | null

  /** NLE timeline with clips on tracks. When present, the compositor reads from this instead of the sequential scene list. */
  timeline?: Timeline | null

  /** Tier 2 file mirror root. User-picked folder per project. Null until first export. */
  tier2Path?: string | null

  /** OKF Layer 0 — project intent / the compass. Null until extracted from the
   *  first prompt. */
  projectBrief?: ProjectBrief | null
}
