/**
 * SearXNG auto-manager — guarantees the free, private local web-search backend
 * is actually RUNNING, not just pointed-at.
 *
 * Research defaults to the chosen model's native search when it has one
 * (Anthropic/OpenAI/Gemini/Qwen — handled in the runner). Every other model
 * (Kimi/DeepSeek/local) searches through `runWebSearch`, whose free path is a
 * self-hosted SearXNG (SEARXNG_URL). The gap this closes: SEARXNG_URL could be
 * SET while nothing listened on it, so `isSearxngReady()` said "ready" and every
 * search hit connection-refused. Here we ensure a `dreambyte-searxng` Docker
 * container is up on :8888 with JSON enabled, so the free path always works.
 *
 * Degrades honestly: a user's own reachable instance is left alone; no Docker →
 * we log guidance and return (research falls back to native/Tavily). Never blocks
 * app boot — call it fire-and-forget.
 */
import { execFile } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { createLogger } from '../lib/logger'

const log = createLogger('electron.searxng-manager')

const DEFAULT_SEARXNG_URL = 'http://localhost:8888'
const CONTAINER_NAME = 'dreambyte-searxng'
const IMAGE = 'searxng/searxng'
const HOST_PORT = 8888
const HEALTH_TIMEOUT_MS = 90_000 // first run pulls the image — allow generous startup
const HEALTH_POLL_MS = 2_000

/** Minimal settings.yml: inherit SearXNG defaults, enable the JSON format our
 *  provider needs, and set a stable secret. Pure + exported for the unit check. */
export function buildSearxngSettingsYaml(secretKey: string): string {
  return [
    '# Generated by Dreambyte — do not edit; delete to regenerate.',
    'use_default_settings: true',
    'server:',
    `  secret_key: "${secretKey}"`,
    'search:',
    '  formats:',
    '    - html',
    '    - json',
    '',
  ].join('\n')
}

function run(cmd: string, args: string[], timeoutMs = 20_000): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    execFile(cmd, args, { timeout: timeoutMs }, (err, stdout, stderr) => {
      const code = err && typeof (err as { code?: unknown }).code === 'number' ? (err as { code: number }).code : err ? 1 : 0
      resolve({ code, stdout: stdout?.toString() ?? '', stderr: stderr?.toString() ?? '' })
    })
  })
}

/** True when the URL answers a JSON search — the real readiness test. */
async function isReachable(url: string): Promise<boolean> {
  try {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), 4000)
    const res = await fetch(`${url}/search?q=ping&format=json`, {
      headers: { Accept: 'application/json' },
      signal: controller.signal,
    }).finally(() => clearTimeout(timer))
    if (!res.ok) return false
    await res.json().catch(() => null)
    return true
  } catch {
    return false
  }
}

function settingsDir(): string {
  // `electron` is required LAZILY, not at module scope.
  //
  // node_modules/electron/index.js resolves the binary path the moment it is
  // required and THROWS "Electron failed to install correctly" when the binary is
  // absent. CI sets ELECTRON_SKIP_BINARY_DOWNLOAD=1, so a top-level
  // `import { app } from 'electron'` made this whole module unloadable there — and
  // searxng-manager.test.ts only wants buildSearxngSettingsYaml, a pure function
  // with no Electron involvement. One import took the entire CI run red.
  //
  // Only this function needs `app`, and it is called exclusively from the Electron
  // main process at runtime, where the binary is present by definition.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { app } = require('electron') as typeof import('electron')
  return path.join(app.getPath('userData'), 'searxng')
}

/** Write settings.yml (with a persisted secret) once; reuse it thereafter. */
function ensureSettingsFile(): string {
  const dir = settingsDir()
  fs.mkdirSync(dir, { recursive: true })
  const file = path.join(dir, 'settings.yml')
  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, buildSearxngSettingsYaml(randomBytes(32).toString('hex')), { mode: 0o600 })
  }
  return dir
}

type DockerStatus = 'ready' | 'daemon-down' | 'missing'

async function dockerStatus(): Promise<DockerStatus> {
  // Server version requires a running daemon; client version works without one.
  const server = await run('docker', ['version', '--format', '{{.Server.Version}}'], 8000)
  if (server.code === 0 && server.stdout.trim()) return 'ready'
  const client = await run('docker', ['--version'], 6000)
  return client.code === 0 ? 'daemon-down' : 'missing'
}

/** Container lifecycle state, or null if it doesn't exist. */
async function containerState(): Promise<'running' | 'stopped' | null> {
  const { code, stdout } = await run('docker', ['inspect', '-f', '{{.State.Running}}', CONTAINER_NAME], 8000)
  if (code !== 0) return null // no such container
  return stdout.trim() === 'true' ? 'running' : 'stopped'
}

async function startContainer(): Promise<boolean> {
  const state = await containerState()
  if (state === 'running') return true
  if (state === 'stopped') {
    const { code, stderr } = await run('docker', ['start', CONTAINER_NAME])
    if (code !== 0) log.warn('searxng: docker start failed', { extra: { stderr: stderr.slice(0, 300) } })
    return code === 0
  }
  const dir = ensureSettingsFile()
  const { code, stderr } = await run(
    'docker',
    [
      'run',
      '-d',
      '--name',
      CONTAINER_NAME,
      '--restart',
      'unless-stopped',
      '-p',
      `${HOST_PORT}:8080`,
      '-v',
      `${dir}:/etc/searxng`,
      IMAGE,
    ],
    300_000, // first run pulls the image (~hundreds of MB) — allow slow networks
  )
  if (code !== 0) {
    log.warn('searxng: docker run failed — research will use native/Tavily search only', {
      extra: { stderr: stderr.slice(0, 400) },
    })
    return false
  }
  return true
}

async function waitHealthy(url: string): Promise<boolean> {
  const deadline = Date.now() + HEALTH_TIMEOUT_MS
  while (Date.now() < deadline) {
    if (await isReachable(url)) return true
    await new Promise((r) => setTimeout(r, HEALTH_POLL_MS))
  }
  return false
}

/**
 * Ensure the free local search backend is live. Idempotent; safe to call on every
 * boot. Fire-and-forget — never awaited in a way that blocks the window.
 */
export async function ensureSearxng(): Promise<void> {
  // Managed SearXNG (self-hosted, private) is OPT-IN — research works out of the
  // box without it via the keyless in-process floor (DuckDuckGo/Brave) and native
  // model search, so we do NOT spin up Docker or default a dead URL by default.
  // Opt in with DREAMBYTE_MANAGE_SEARXNG=1 to auto-run a local instance. A user's
  // own SEARXNG_URL is honored by runWebSearch regardless of this flag.
  if (process.env.DREAMBYTE_MANAGE_SEARXNG !== '1') return

  const url = (process.env.SEARXNG_URL?.trim() || DEFAULT_SEARXNG_URL).replace(/\/+$/, '')
  process.env.SEARXNG_URL = url

  // Already up (our container from a prior boot, or the user's own instance)? Done.
  if (await isReachable(url)) {
    log.info('searxng: reachable', { extra: { url } })
    return
  }

  // We only manage the default localhost instance. A custom/remote URL that's
  // down is the user's to fix — don't spawn a container that won't match it.
  const isDefault = url === DEFAULT_SEARXNG_URL
  if (!isDefault) {
    log.warn('searxng: configured URL is unreachable and not the managed default — leaving it to you', {
      extra: { url },
    })
    return
  }

  const docker = await dockerStatus()
  if (docker !== 'ready') {
    const why =
      docker === 'daemon-down'
        ? 'Docker is installed but not running — start Docker Desktop to enable free local web search.'
        : 'Docker not found — install it (or set TAVILY_API_KEY / use a model with native search) to enable research.'
    log.warn(`searxng: ${why}`)
    return
  }

  log.info('searxng: starting managed container (first run pulls the image, ~1–2 min)')
  if (!(await startContainer())) return
  const healthy = await waitHealthy(url)
  log.info(`searxng: ${healthy ? 'live' : 'started but not answering yet — will be used once it is'}`, {
    extra: { url },
  })
}
