/**
 * gen-okf-viz — OKF bundle tooling.
 *
 *  1. Generate the bundle-root `index.md` (with `okf_version`) — the tag
 *     router over the craft packs. Does NOT touch src/lib/skills/library/index.md
 *     (already generated by gen-okf-index.ts).
 *  2. Render a single self-contained HTML visualizer of the whole knowledge
 *     bundle — a Cytoscape graph coloured by type, clustered by tag — to
 *     docs/okf-bundle.html. "See everything the agent knows."
 *
 * Run: npx tsx scripts/okf/gen-okf-viz.ts
 */
import fs from 'fs'
import path from 'path'
import { walkOkfBundle, canonicalBundleRoots, type OkfBundle } from '../../src/lib/agents/okf/bundle'

const CWD = process.cwd()
const DREAMBYTE_DIR = path.join(CWD, '.claude', 'skills', 'dreambyte')

/**
 * The bundle-root index.md: OKF version + the routing-tag contract + a line per craft
 * pack, derived from the packs on disk.
 * The root index lists the packs directly; there is no separate rules/index.md
 * catalog to drift from each pack's own frontmatter.
 */
function writeIndexMd(bundle: OkfBundle): string[] {
  const written: string[] = []
  const packs = bundle.nodes.filter((n) => n.group === 'rules').sort((a, b) => a.id.localeCompare(b.id))
  const root = [
    '---',
    'okf_version: "0.1"',
    '---',
    '# Dreambyte Knowledge Bundle',
    '',
    'OKF v0.1 conformant. Generated by `scripts/okf/gen-okf-viz.ts` — do not hand-edit the index files.',
    '',
    '## Craft packs',
    '',
    ...packs.map((n) => `* [${n.title}](/rules/${n.id.split('/').pop()}.md) [${n.tags.join(', ')}]${n.description ? ` - ${n.description}` : ''}`),
    '',
    '* Skill library lives at `src/lib/skills/library/` (renderer skills; its own index.md).',
    '',
    '## Routing tags',
    '',
    'A craft `rule` carries `tags` that decide when it is injected (intent-router selects',
    'by tag intersection). This vocabulary is the bundle\'s routing contract — documented',
    'here so any consumer can route without reading the TS:',
    '',
    '- `core` — routed for every video (audio).',
    '- `lane:media` / `lane:avatar` — routed when the brief sources media / is avatar-centric.',
    '- `renderer` — routable on demand via `get_routed_craft({ pack })`, not intent-routed.',
    '',
  ].join('\n')
  const rootOut = path.join(DREAMBYTE_DIR, 'index.md')
  fs.writeFileSync(rootOut, root)
  written.push(path.relative(CWD, rootOut))
  return written
}

function renderHtml(bundle: OkfBundle): string {
  // Concept nodes + tag-hub nodes + edges as Cytoscape elements.
  const elements = [
    ...bundle.nodes.map((n) => ({
      data: { id: n.id, label: n.title, kind: n.type, group: n.group, description: n.description, tags: n.tags.join(', ') },
    })),
    ...bundle.tagHubs.map((id) => ({ data: { id, label: id.replace(/^tag:/, '#'), kind: 'tag', group: 'tag' } })),
    ...bundle.edges.map((e, i) => ({ data: { id: `e${i}`, source: e.source, target: e.target, kind: e.kind } })),
  ]
  const json = JSON.stringify(elements)
  const counts = bundle.nodes.reduce<Record<string, number>>((m, n) => ((m[n.type] = (m[n.type] ?? 0) + 1), m), {})
  const summary = Object.entries(counts)
    .map(([t, c]) => `${c} ${t}`)
    .join(' · ')
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Dreambyte OKF Bundle</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.30.2/cytoscape.min.js" integrity="sha512-EY3U1MWdgKx0P1dqTE4inlKz2cpXtWpsR1YUyD855Hs6RL/A0cyvrKh60EpE8wDZ814cTe1KgRK+sG0Rn792vQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<style>
  body{margin:0;font:14px/1.5 system-ui,sans-serif;background:#0f1115;color:#e6e6e6}
  #bar{padding:10px 16px;background:#171a21;border-bottom:1px solid #2a2f3a}
  #bar b{color:#fff} #bar span{color:#8b95a7}
  #cy{position:absolute;top:48px;left:0;right:320px;bottom:0}
  #panel{position:absolute;top:48px;right:0;width:320px;bottom:0;background:#171a21;border-left:1px solid #2a2f3a;padding:16px;overflow:auto;box-sizing:border-box}
  #panel h2{font-size:16px;margin:.2em 0} #panel .t{color:#8b95a7;font-size:12px;text-transform:uppercase;letter-spacing:.05em}
  #panel .tags{margin-top:8px} #panel .tag{display:inline-block;background:#2a2f3a;border-radius:10px;padding:2px 8px;margin:2px;font-size:12px}
  .legend{margin-top:8px} .legend i{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:4px}
</style></head><body>
<div id="bar"><b>Dreambyte OKF Bundle</b> &nbsp;<span>${bundle.nodes.length} concepts · ${summary} · ${bundle.tagHubs.length} tags</span></div>
<div id="cy"></div>
<div id="panel"><div class="t">click a node</div><h2>Knowledge graph</h2><p style="color:#8b95a7">Concepts coloured by type, clustered by shared tag. Click any node for its frontmatter.</p>
<div class="legend">
<div><i style="background:#4ea1ff"></i>rule</div><div><i style="background:#7bd88f"></i>skill</div>
<div><i style="background:#e8a420"></i>playbook</div><div><i style="background:#c084fc"></i>doctrine</div>
<div><i style="background:#f87171"></i>guide</div><div><i style="background:#3a3f4a"></i>tag</div></div></div>
<script>
const ELEMENTS = ${json};
const COLOR = { rule:'#4ea1ff', skill:'#7bd88f', playbook:'#e8a420', doctrine:'#c084fc', guide:'#f87171', tag:'#3a3f4a', unknown:'#888' };
const cy = cytoscape({
  container: document.getElementById('cy'),
  elements: ELEMENTS,
  style: [
    { selector:'node', style:{ 'background-color': n => COLOR[n.data('kind')]||'#888', 'label':'data(label)', 'color':'#cdd3df','font-size':'9px','text-wrap':'wrap','text-max-width':'90px' } },
    { selector:'node[kind="tag"]', style:{ 'shape':'round-rectangle','background-color':'#3a3f4a','color':'#8b95a7','font-size':'8px' } },
    { selector:'edge', style:{ 'width':1,'line-color':'#2a2f3a','curve-style':'haystack','opacity':0.6 } },
    { selector:'node:selected', style:{ 'border-width':3,'border-color':'#fff' } },
  ],
  layout: { name:'cose', animate:false, nodeRepulsion:8000, idealEdgeLength:70 },
});
const panel = document.getElementById('panel');
// Escape all interpolated bundle text — defense-in-depth against a hostile
// title/description/tag in a knowledge file injecting markup via innerHTML.
const esc = s => String(s==null?'':s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
cy.on('tap','node', e=>{ const d=e.target.data();
  if(d.kind==='tag'){ panel.innerHTML='<div class="t">tag</div><h2>'+esc(d.label)+'</h2><p style="color:#8b95a7">'+e.target.degree()+' concepts share this tag.</p>'; return; }
  panel.innerHTML='<div class="t">'+esc(d.kind)+' · '+esc(d.group)+'</div><h2>'+esc(d.label)+'</h2><p>'+esc(d.description||'')+'</p>'+
    (d.tags?'<div class="tags">'+d.tags.split(', ').filter(Boolean).map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</div>':'');
});
</script></body></html>
`
}

function main() {
  const bundle = walkOkfBundle(canonicalBundleRoots(CWD))
  const indexes = writeIndexMd(bundle)
  const html = renderHtml(bundle)
  const out = path.join(CWD, 'docs', 'okf-bundle.html')
  fs.writeFileSync(out, html)
  console.log(`[gen-okf-viz] ${bundle.nodes.length} concepts, ${bundle.tagHubs.length} tags, ${bundle.edges.length} edges`)
  console.log(`[gen-okf-viz] wrote index files: ${indexes.join(', ')}`)
  console.log(`[gen-okf-viz] wrote visualizer: ${path.relative(CWD, out)}`)
}

main()
