#!/usr/bin/env tsx
/**
 * gen-okf-index — generate the OKF substrate's derived artifacts and stale-gate
 * them across every on-disk root.
 *
 * The skill registry (src/lib/skills/library/*.md) is
 * the FILE OF RECORD. The artifacts this script produces are GENERATED VIEWS —
 * hand-editing any of them is a bug the CI stale-gate
 * (scripts/okf/gen-okf-index.test.ts) catches by regenerating and diffing.
 *
 * Generated artifacts:
 *   1. src/lib/skills/library/index.md
 *        A negative-framed catalog of every registered skill, built from
 *        getAllSkillIds() + metadata. Each line: `id — does X; reach for it
 *        when Y; skipping risks Z`.
 *   2. three.md de-dup
 *        The Three.js craft pack has a single source of record at
 *        .claude/skills/dreambyte/rules/three.md. The .agents copy is a
 *        generated mirror of it (no content lost; the duplicate is now a view).
 *
 * design-principles.md and design-brief.md USED to be generated here from
 * src/lib/generation/*.ts. Both rule packs were deleted in the 22→4 corpus cut; the
 * emitters went with them, or `npm run gen:okf` would resurrect the files.
 *
 * Usage:
 *   npx tsx scripts/okf/gen-okf-index.ts            # write all artifacts
 *   npx tsx scripts/okf/gen-okf-index.ts --check    # exit 1 if any artifact is stale
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import {
  getCuratedSkillIds,
  getSkillMetadata,
} from '../../src/lib/skills/registry'
import type { SkillMetadata } from '../../src/lib/skills/types'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
export const REPO_ROOT = path.resolve(__dirname, '..', '..')

// ── Generated artifact paths ─────────────────────────────────────────────────

export const INDEX_PATH = path.join(REPO_ROOT, 'src', 'lib', 'skills', 'library', 'index.md')

/** three.md: source of record (.claude) + the generated mirror (.agents). */
export const THREE_SOURCE_PATH = path.join(
  REPO_ROOT,
  '.claude',
  'skills',
  'dreambyte',
  'rules',
  'three.md',
)
export const THREE_MIRROR_PATH = path.join(
  REPO_ROOT,
  '.agents',
  'skills',
  'dreambyte',
  'rules',
  'three.md',
)

const GENERATED_BANNER =
  '<!-- GENERATED by scripts/okf/gen-okf-index.ts — do not edit by hand. Edit the file of record, then run `npm run gen:okf`. -->'

// ── 1. index.md ───────────────────────────────────────────────────────────────

/**
 * Negative-framed one-liners. Keyed by skill id. The first clause ("does X")
 * must be UNIQUE across all skills (lint enforces it) so the plan phase can
 * disambiguate. Format: { does, when, risk }.
 *
 * These are derived from each skill's own description/tags — they restate the
 * registry's intent in routing terms, they do not add new doctrine. If a skill is added to the library without an entry here,
 * generation falls back to its description and the first-clause-unique lint
 * still guards collisions.
 */
const FRAMINGS: Record<string, { does: string; when: string; risk: string }> = {
  'canvas2d-animation': {
    does: 'draws expressive hand-drawn / procedural art on a 2D canvas (pen, marker, chalk, brush)',
    when: 'the scene wants a whiteboard/chalkboard feel, sketched strokes, or particle/procedural texture',
    risk: 'reaching for SVG or Motion instead gives clean vector geometry that reads as generic, not hand-made',
  },
  'svg-animation': {
    does: 'animates clean vector graphics with CSS/SMIL inside an SVG viewBox',
    when: 'the content is simple flat vector shapes that need lightweight, crisp motion',
    risk: 'using Canvas2D or Three.js over-engineers a flat graphic and loses vector crispness',
  },
  'd3-data-visualization': {
    does: 'builds data visualizations and charts (bar, line, pie, scatter, gauge) with D3',
    when: 'the scene presents real numeric data, comparisons, or dashboards',
    risk: 'faking a chart in Motion/SVG yields mis-scaled axes and unreadable data',
  },
  'motion-css-animation': {
    does: 'orchestrates layout-heavy explainers with the anime.js master timeline, text splitting, and DreambyteMotion',
    when: 'the scene is text reveals, staggered element entrances, or a typographic explainer beat',
    risk: 'hand-rolling reveals without the timeline produces uncoordinated, janky staggers',
  },
  'lottie-animation': {
    does: 'renders precise keyframed vector animations from Lottie/bodymovin JSON',
    when: 'the scene needs micro-animations, icon motion, or designer-authored keyframe control',
    risk: 'approximating Lottie motion in CSS drops the precise easing and motion personality',
  },
  'threejs-3d-scene': {
    does: 'composes immersive 3D scenes with PBR materials, environments, and camera flyovers (Three.js r183)',
    when: 'the content is genuinely spatial — 3D products, environments, WebGL effects, 3D scatter',
    risk: 'simulating depth in 2D looks flat; stacking 3D on a 2D idea wastes a heavy renderer',
  },
  '3d-world-scene': {
    does: 'places objects and floating text panels in a preset 3D world with an animated camera path',
    when: 'the scene is a narrated walkthrough of a 3D environment (meadow / studio / void)',
    risk: 'building a bespoke Three.js scene re-implements the world/camera scaffolding by hand',
  },
}

function framingFor(meta: SkillMetadata): { does: string; when: string; risk: string } {
  const f = FRAMINGS[meta.id]
  if (f) return f
  // Fallback for a newly-added skill without a hand-written framing: derive
  // from its own description so index.md still generates (and the lint still
  // guards first-clause collisions).
  return {
    does: meta.description.replace(/\s+/g, ' ').trim() || `provides the ${meta.title} capability`,
    when: `the scene targets ${meta.sceneType} (${meta.category})`,
    risk: 'omitting it forces a less-suited renderer for this scene type',
  }
}

export function buildIndexMarkdown(): string {
  // CURATED-ONLY: index.md is repo-tracked, so it must never bake in machine-
  // local distilled-style hash ids (which would flap the CI stale-gate).
  const ids = getCuratedSkillIds().slice().sort()
  const metas = new Map(getSkillMetadata(ids).map((m) => [m.id, m]))

  const lines: string[] = []
  lines.push('---')
  lines.push('type: index')
  lines.push('title: Skill Catalog Index')
  lines.push('description: Negative-framed routing catalog of every registered renderer skill — read this in the plan phase to pick skills.')
  lines.push('tags: [okf, index, routing, skills]')
  lines.push('timestamp: ' + isoDate())
  lines.push('---')
  lines.push('')
  lines.push(GENERATED_BANNER)
  lines.push('')
  lines.push('# Skill Catalog Index')
  lines.push('')

  for (const id of ids) {
    const meta = metas.get(id)
    if (!meta) continue
    const f = framingFor(meta)
    lines.push(`- \`${id}\` — ${f.does}; reach for it when ${f.when}; skipping risks ${f.risk}.`)
  }
  lines.push('')
  return lines.join('\n')
}

// ── 3. three.md mirror ─────────────────────────────────────────────────────────

export function buildThreeMirror(): string {
  // The mirror is a byte-for-byte copy of the source of record so the de-dup
  // can never drift. We do NOT inject a banner (it would change content and the
  // file is large, narrative prose with code blocks); the stale-gate compares
  // mirror === source directly.
  return fs.readFileSync(THREE_SOURCE_PATH, 'utf-8')
}

// ── Lints ───────────────────────────────────────────────────────────────────

/**
 * Pure collision detector over (id, firstClause) pairs. Extracted so the lint
 * is testable with a synthetic collision without mutating the real registry.
 */
export function findFirstClauseCollisions(entries: { id: string; firstClause: string }[]): string[] {
  const seen = new Map<string, string>()
  const errors: string[] = []
  for (const { id, firstClause } of entries) {
    const key = firstClause.trim().toLowerCase()
    const prior = seen.get(key)
    if (prior) {
      errors.push(`first-clause collision: "${id}" and "${prior}" share the opening clause "${key}"`)
    } else {
      seen.set(key, id)
    }
  }
  return errors
}

/** No two skills may share their first clause ("does X") — the routing signal. */
export function lintFirstClauseUnique(): string[] {
  // CURATED-ONLY — match buildIndexMarkdown()'s scope (distilled styles are not
  // in index.md, so their first clauses can't collide there).
  const ids = getCuratedSkillIds().slice().sort()
  const metas = new Map(getSkillMetadata(ids).map((m) => [m.id, m]))
  const entries: { id: string; firstClause: string }[] = []
  for (const id of ids) {
    const meta = metas.get(id)
    if (!meta) continue
    entries.push({ id, firstClause: framingFor(meta).does })
  }
  return findFirstClauseCollisions(entries)
}

/**
 * No-duplicate-concept lint: the prose doctrine (three.md) must have exactly
 * ONE source of record. The generator's PLANNED mirror content must equal the
 * .claude source of record (the de-dup contract). We compare planned-vs-source
 * rather than disk-vs-source so the lint never blocks the very write that
 * brings a stale mirror back into sync — the stale-gate (disk-vs-planned)
 * covers a hand-edited mirror separately.
 */
export function lintNoDuplicateConcept(): string[] {
  const errors: string[] = []
  const source = fs.readFileSync(THREE_SOURCE_PATH, 'utf-8')
  const plannedMirror = buildThreeMirror()
  if (plannedMirror !== source) {
    errors.push(
      'three.md de-dup broken: generated .agents mirror would not equal the .claude source of record',
    )
  }
  return errors
}

/**
 * Cross-link-resolves lint: every relative markdown link in a generated file
 * must point at a file that exists.
 */
export function lintCrossLinksResolve(): string[] {
  const errors: string[] = []
  const linkRe = /\[[^\]]*\]\(([^)]+)\)|`((?:\.\.?\/)[^`]+\.md)`/g

  // Planned generated files count as "existing" so a link to a not-yet-written
  // artifact still resolves on a clean checkout.
  const plannedPaths = new Set(plannedTargets().map((t) => path.resolve(t.path)))

  const checked: { file: string; content: string }[] = [
    { file: INDEX_PATH, content: buildIndexMarkdown() },
  ]

  for (const { file, content } of checked) {
    const dir = path.dirname(file)
    let m: RegExpExecArray | null
    linkRe.lastIndex = 0
    while ((m = linkRe.exec(content)) !== null) {
      const target = (m[1] || m[2] || '').trim()
      if (!target) continue
      // Only resolve relative links to .md concept files.
      if (!target.endsWith('.md')) continue
      if (/^https?:/.test(target)) continue
      const stripped = target.split('#')[0]
      if (!stripped.startsWith('.')) continue
      const resolved = path.resolve(dir, stripped)
      if (!fs.existsSync(resolved) && !plannedPaths.has(resolved)) {
        errors.push(`broken cross-link in ${path.relative(REPO_ROOT, file)}: "${target}"`)
      }
    }
  }
  return errors
}

// ── Plan: every generated file + its desired content ──────────────────────────

export interface GenTarget {
  path: string
  content: string
}

export function plannedTargets(): GenTarget[] {
  const targets: GenTarget[] = []
  targets.push({ path: INDEX_PATH, content: buildIndexMarkdown() })
  targets.push({ path: THREE_MIRROR_PATH, content: buildThreeMirror() })
  return targets
}

export function allLints(): string[] {
  return [
    ...lintFirstClauseUnique(),
    ...lintNoDuplicateConcept(),
    ...lintCrossLinksResolve(),
  ]
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function isoDate(): string {
  // Deterministic per-day stamp so re-running on the same day is a no-op for
  // the stale-gate. (Timestamp is a freshness marker, not a content hash.)
  return new Date().toISOString().slice(0, 10)
}

function readIfExists(p: string): string | null {
  try {
    return fs.readFileSync(p, 'utf-8')
  } catch {
    return null
  }
}

/**
 * Drop the `timestamp:` frontmatter line before comparing. The timestamp is a
 * per-day freshness marker (isoDate), NOT part of the file-of-record — including
 * it in the stale comparison made the gate flap red every day after generation
 * (disk holds generation-day's date; a fresh regen holds today's). The gate must
 * compare content, not the freshness stamp.
 */
function stripTimestamp(s: string): string {
  return s.replace(/^timestamp: .*$\n?/m, '')
}

/** Returns the list of stale (or missing) generated files + lint errors. */
export function checkStale(): { stale: string[]; lints: string[] } {
  const stale: string[] = []
  for (const t of plannedTargets()) {
    const current = readIfExists(t.path)
    if (current === null || stripTimestamp(current) !== stripTimestamp(t.content)) {
      stale.push(path.relative(REPO_ROOT, t.path))
    }
  }
  return { stale, lints: allLints() }
}

export function writeAll(): string[] {
  const written: string[] = []
  for (const t of plannedTargets()) {
    fs.mkdirSync(path.dirname(t.path), { recursive: true })
    fs.writeFileSync(t.path, t.content, 'utf-8')
    written.push(path.relative(REPO_ROOT, t.path))
  }
  return written
}

// ── CLI ────────────────────────────────────────────────────────────────────────

function main() {
  const check = process.argv.includes('--check')
  if (check) {
    const { stale, lints } = checkStale()
    if (stale.length === 0 && lints.length === 0) {
      console.log('✓ OKF substrate is up to date.')
      process.exit(0)
    }
    if (stale.length) {
      console.error('✗ Stale generated files (run `npm run gen:okf`):')
      for (const f of stale) console.error('  - ' + f)
    }
    if (lints.length) {
      console.error('✗ Lint failures:')
      for (const e of lints) console.error('  - ' + e)
    }
    process.exit(1)
  }

  const lints = allLints()
  if (lints.length) {
    console.error('✗ Refusing to write — lint failures:')
    for (const e of lints) console.error('  - ' + e)
    process.exit(1)
  }
  const written = writeAll()
  console.log('✓ Wrote OKF substrate artifacts:')
  for (const f of written) console.log('  - ' + f)
}

// Run when invoked directly (not when imported by the stale-gate test).
const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invokedDirectly) main()
